services:
  postgres-db-estoques:
    image: postgres:16-alpine
    container_name: EstoquesPostgre
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - estoques_postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  estoques_postgres_data:
    name: estoques_postgres_data