// <auto-generated />
using System;
using Estoques.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Estoques.Infra.Data.Migrations
{
    [DbContext(typeof(EstoquesDbContext))]
    partial class EstoquesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Estoques.Domain.Entities.Adquirente", b =>
                {
                    b.Property<int>("IDAdquirente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDAdquirente"));

                    b.Property<int>("IDUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("NMAdquirente")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TXAnotacao")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("TXEndereco")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IDAdquirente");

                    b.HasIndex("IDUsuario");

                    b.ToTable("Adquirente", (string)null);
                });

            modelBuilder.Entity("Estoques.Domain.Entities.Fornecedor", b =>
                {
                    b.Property<int>("IDFornecedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDFornecedor"));

                    b.Property<int>("IDUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("NMFornecedor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TXAnotacao")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("TXEndereco")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IDFornecedor");

                    b.HasIndex("IDUsuario");

                    b.ToTable("Fornecedor", (string)null);
                });

            modelBuilder.Entity("Estoques.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("IDProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDProduto"));

                    b.Property<string>("DSProduto")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("IDProdutoFabricante")
                        .HasColumnType("integer");

                    b.Property<int?>("IDProdutoMedida")
                        .HasColumnType("integer");

                    b.Property<int>("IDProdutoSituacao")
                        .HasColumnType("integer");

                    b.Property<int>("IDProdutoTipo")
                        .HasColumnType("integer");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("integer");

                    b.Property<byte>("INProdutoCor")
                        .HasColumnType("smallint");

                    b.Property<string>("LKProdutoImagem")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("NMProduto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("QTProduto")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TXAnotacao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IDProduto");

                    b.HasIndex("IDProdutoFabricante");

                    b.HasIndex("IDProdutoMedida");

                    b.HasIndex("IDProdutoSituacao");

                    b.HasIndex("IDProdutoTipo");

                    b.HasIndex("IDUsuario");

                    b.ToTable("Produto", (string)null);
                });

            modelBuilder.Entity("Estoques.Domain.Entities.ProdutoFabricante", b =>
                {
                    b.Property<int>("IDProdutoFabricante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDProdutoFabricante"));

                    b.Property<int>("IDUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("NMProdutoFabricante")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IDProdutoFabricante");

                    b.HasIndex("IDUsuario");

                    b.ToTable("ProdutoFabricante", (string)null);
                });

            modelBuilder.Entity("Estoques.Domain.Entities.ProdutoHistorico", b =>
                {
                    b.Property<int>("IDProdutoHistorico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDProdutoHistorico"));

                    b.Property<DateTime>("DTProdutoHistorico")
                        .HasColumnType("date");

                    b.Property<int?>("IDAdquirente")
                        .HasColumnType("integer");

                    b.Property<int>("IDFornecedor")
                        .HasColumnType("integer");

                    b.Property<int>("IDProduto")
                        .HasColumnType("integer");

                    b.Property<byte>("INProdutoHistoricoTipo")
                        .HasColumnType("smallint");

                    b.Property<decimal>("QTProdutoHistorico")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("VLProdutoHistorico")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("IDProdutoHistorico");

                    b.HasIndex("IDAdquirente");

                    b.HasIndex("IDFornecedor");

                    b.HasIndex("IDProduto");

                    b.ToTable("ProdutoHistorico", (string)null);
                });

            modelBuilder.Entity("Estoques.Domain.Entities.ProdutoMedida", b =>
                {
                    b.Property<int>("IDProdutoMedida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDProdutoMedida"));

                    b.Property<int>("IDUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("MDProdutoMedida")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IDProdutoMedida");

                    b.HasIndex("IDUsuario");

                    b.ToTable("ProdutoMedida", (string)null);
                });

            modelBuilder.Entity("Estoques.Domain.Entities.ProdutoSituacao", b =>
                {
                    b.Property<int>("IDProdutoSituacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDProdutoSituacao"));

                    b.Property<int>("IDUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("NMProdutoSituacao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IDProdutoSituacao");

                    b.HasIndex("IDUsuario");

                    b.ToTable("ProdutoSituacao", (string)null);
                });

            modelBuilder.Entity("Estoques.Domain.Entities.ProdutoTipo", b =>
                {
                    b.Property<int>("IDProdutoTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDProdutoTipo"));

                    b.Property<int>("IDUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("NMProdutoTipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IDProdutoTipo");

                    b.HasIndex("IDUsuario");

                    b.ToTable("ProdutoTipo", (string)null);
                });

            modelBuilder.Entity("Estoques.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IDUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDUsuario"));

                    b.Property<string>("CDSenha")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("NMLogin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NMUsuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IDUsuario");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Estoques.Domain.Entities.Adquirente", b =>
                {
                    b.HasOne("Estoques.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Adquirentes")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Estoques.Domain.Entities.Fornecedor", b =>
                {
                    b.HasOne("Estoques.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Fornecedores")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Estoques.Domain.Entities.Produto", b =>
                {
                    b.HasOne("Estoques.Domain.Entities.ProdutoFabricante", "ProdutoFabricante")
                        .WithMany("Produtos")
                        .HasForeignKey("IDProdutoFabricante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Estoques.Domain.Entities.ProdutoMedida", "ProdutoMedida")
                        .WithMany("Produtos")
                        .HasForeignKey("IDProdutoMedida")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Estoques.Domain.Entities.ProdutoSituacao", "ProdutoSituacao")
                        .WithMany("Produtos")
                        .HasForeignKey("IDProdutoSituacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Estoques.Domain.Entities.ProdutoTipo", "ProdutoTipo")
                        .WithMany("Produtos")
                        .HasForeignKey("IDProdutoTipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Estoques.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Produtos")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProdutoFabricante");

                    b.Navigation("ProdutoMedida");

                    b.Navigation("ProdutoSituacao");

                    b.Navigation("ProdutoTipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Estoques.Domain.Entities.ProdutoFabricante", b =>
                {
                    b.HasOne("Estoques.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ProdutosFabricantes")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Estoques.Domain.Entities.ProdutoHistorico", b =>
                {
                    b.HasOne("Estoques.Domain.Entities.Adquirente", "Adquirente")
                        .WithMany("ProdutosHistoricos")
                        .HasForeignKey("IDAdquirente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Estoques.Domain.Entities.Fornecedor", "Fornecedor")
                        .WithMany("ProdutosHistoricos")
                        .HasForeignKey("IDFornecedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Estoques.Domain.Entities.Produto", "Produto")
                        .WithMany("ProdutosHistoricos")
                        .HasForeignKey("IDProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adquirente");

                    b.Navigation("Fornecedor");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Estoques.Domain.Entities.ProdutoMedida", b =>
                {
                    b.HasOne("Estoques.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ProdutosMedidas")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Estoques.Domain.Entities.ProdutoSituacao", b =>
                {
                    b.HasOne("Estoques.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ProdutosSituacoes")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Estoques.Domain.Entities.ProdutoTipo", b =>
                {
                    b.HasOne("Estoques.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ProdutosTipos")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Estoques.Domain.Entities.Adquirente", b =>
                {
                    b.Navigation("ProdutosHistoricos");
                });

            modelBuilder.Entity("Estoques.Domain.Entities.Fornecedor", b =>
                {
                    b.Navigation("ProdutosHistoricos");
                });

            modelBuilder.Entity("Estoques.Domain.Entities.Produto", b =>
                {
                    b.Navigation("ProdutosHistoricos");
                });

            modelBuilder.Entity("Estoques.Domain.Entities.ProdutoFabricante", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Estoques.Domain.Entities.ProdutoMedida", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Estoques.Domain.Entities.ProdutoSituacao", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Estoques.Domain.Entities.ProdutoTipo", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Estoques.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Adquirentes");

                    b.Navigation("Fornecedores");

                    b.Navigation("Produtos");

                    b.Navigation("ProdutosFabricantes");

                    b.Navigation("ProdutosMedidas");

                    b.Navigation("ProdutosSituacoes");

                    b.Navigation("ProdutosTipos");
                });
#pragma warning restore 612, 618
        }
    }
}
